Added a CLI for users to download models
OpenMDAO/Aviary pull request #122
Opened 2024-01-30 19:17 UTC by crecine

### Summary

Allows users that pip installed Aviary to download example models

### Related Issues

- Resolves #

### Backwards incompatibilities

None

### New Dependencies

None

2024-01-30 20:44 UTC, johnjasa requested changes
Fun stuff, great implementation, I love the docs and tests, thank you! Got it working well locally and enjoy it. Few quick notes and suggestions.

2024-01-30 20:44 UTC, johnjasa commented on aviary/docs/user_guide/aviary_commands.ipynb
> +    "This can be specified as the name of the file, the path from aviary/models, the name of a folder in aviary/models. Multiple files and folders can be downloaded at once.\n",
Please add a link to the GitHub repo at aviary/models so people can see what's available

2024-01-30 20:44 UTC, johnjasa commented on aviary/docs/user_guide/aviary_commands.ipynb
> +    "(aviary-hanger-command)=\n",
please rename `hanger` to `hangar` throughout

2024-01-30 20:44 UTC, johnjasa commented on aviary/interface/download_models.py
> +        'input_decks', metavar='indecks', type=str, nargs='+', help='Name of vehicle input deck file'
When I do `aviary hanger` to get help, I see `indecks       Name of vehicle input deck file`, but I believe this also includes engine decks or other possible files, not just vehicle decks. Could you please update this docstring to reflect that?

2024-01-30 21:29 UTC, johnjasa approved these changes
Thanks for the quick update!

2024-01-31 17:38 UTC, jkirk5 approved these changes
Looks good, nice tests!

2024-01-31 17:38 UTC, jkirk5 commented on aviary/docs/user_guide/aviary_commands.ipynb
Line 9: typo "caller"

Can you change the wording from "download" to "copy"? It kind of sounds like it is pulling a fresh copy from the repo or something, but that's not the case. I see "download" in other places that should get updated too

2024-01-31 18:15 UTC, merged