Refactor assert that checks whether the variable hierarchy is in proper alphabetical order.
OpenMDAO/Aviary pull request #335
Opened 2024-06-18 23:03 UTC by Kenneth-T-Moore

### Summary

Refactor the assert that checks whether the variable hierarchy is in proper alphabetical order so that it is cleaner and works with arbitrary depth.

### Related Issues

- Resolves #

### Backwards incompatibilities

None

### New Dependencies

None

2024-06-20 18:07 UTC, crecine approved these changes

2024-06-21 17:55 UTC, jkirk5 requested changes
Tested with a multi-level variable hierarchy - unexpected behavior. Alphabetization required hierarchy to be formatted like:
```
class A:
    b= 'var1'
    class C:
        x = 'another_var'
    cb='var_cb'
    cx='var_cx'
    class D:
        var='var'
 etc...
```
 
 Which is hard to read. Do we have a clean way to allow for subclass definitions to be group together and not distributed amongst the other variables at that higher class level?

2024-06-21 18:55 UTC, Kenneth-T-Moore commented
Thanks for testing it out, Jason. Yeah, that doesn't look ideal, so I reworked the logic to allow the subclasses to be listed after the variables, which is much more readable.

2024-06-24 21:29 UTC, jkirk5 approved these changes

2024-06-24 21:53 UTC, merged