Addition of Fuselage Engine Modeling
OpenMDAO/Aviary pull request #463
Opened 2024-07-26 20:12 UTC by Dawson-Manning

### Summary

This commit increases Aviary's (version: 0.9.4-dev) functionality by adding statements to allow of the modeling of aircraft that only utilize fuselage engines. Previously modeling aircraft that only use fuselage mounted engines was not supported. This addition was checked with models that have no wing engines (2 fuselage engines), 2 wing engines (no fuselage engines), and 4 wing engines (no fuselage engines) and all optimized successfully. Before and after edit images attached.
![Screenshot 2024-07-26 142041](https://github.com/user-attachments/assets/2d2bc171-52b9-46ac-af29-db68c0a09804)
![Screenshot 2024-07-26 142014](https://github.com/user-attachments/assets/d2af38df-0a1e-499e-b9f6-e04257f2b8a2)

### Related Issues

- Resolves Issue #342

### Backwards incompatibilities

None

### New Dependencies

None

2024-07-31 12:49 UTC, Dawson-Manning commented
Corrections made to fix failure of "test_wing_detailed.py:DetailedWingBendingTest.test_case_multiengine"

2024-08-07 22:01 UTC, Kenneth-T-Moore commented on aviary/subsystems/mass/flops_based/wing_detailed.py
> +            else:
I verified with Jason that this is the right behavior.

2024-08-07 22:02 UTC, Kenneth-T-Moore commented on aviary/subsystems/mass/flops_based/wing_detailed.py
> +                else:
Probably don't need the "else" branch anymore, since num_wing_engines=0 bails before it reaches this code now.

2024-08-08 14:20 UTC, Kenneth-T-Moore approved these changes
Looks good.

2024-08-15 13:34 UTC, jkirk5 requested changes
Test values need additional investigation (addition of wing engines did not change bending factor for the multiengine test

2024-12-30 20:07 UTC, jkirk5 approved these changes
I resolved the edge case for multiple engines of a given type (multi-engine ended up being fine)

2024-12-31 18:50 UTC, merged