Added missing lines needed for generation of 3d model display in dashboard
OpenMDAO/Aviary pull request #465
Opened 2024-07-29 13:17 UTC by hschilling

Added missing lines needed for generation of 3d model display in dashboard

### Summary

Somehow the lines needed to put the 3d entities into the dashboard 3d model display HTML file were missing. 

### Related Issues

- Resolves #460 

### Backwards incompatibilities

None

### New Dependencies

None

2024-07-29 19:16 UTC, Kenneth-T-Moore approved these changes

2024-07-29 20:02 UTC, johnjasa requested changes
Thanks for this, Herb!

I tried running it locally after running `run_basic_aviary_example.py` but got this error:
```
/mnt/c/Users/John/Dropbox/git/om-Aviary/aviary/visualization/dashboard.py:691: OpenMDAOWarning:Unable to create aircraft 3D model display due to error 'Variable name "pre_mission.core_subsystems.core_geometry.characteristic_lengths.aircraft:fuselage:length" not found.'
problem
```

Do you see the same behavior locally? Or do I need to call the example differently?

Separately, I pushed up a change to have the aircraft 3d model tab always visible and display the error in that tab if it fails. I found that I didn't look at the terminal error and was confused about where the model tab was. Feel free to remove or change this; it seemed a little more naive-user-proof to me.

2024-08-06 16:27 UTC, crecine approved these changes
Once you address John's comment, this looks good to me.

2024-08-06 17:27 UTC, hschilling commented
> Once you address John's comment, this looks good to me.

I actually did. This code fixes that

```try:
            val = self._final_case[var_prom_name]
            return float(val)
        except KeyError as e:
            pass
```

2024-08-06 19:24 UTC, merged