Turboprop unit test
OpenMDAO/Aviary pull request #468
Opened 2024-07-29 21:05 UTC by xjjiang

### Summary

1. added back `check_partials` in `test_electroprop` of `test_turboprop_model.py`.
2. in `PreHamiltonStandard` class, check whether inputs are valid.
3. in `PostHamiltonStandard` class, set propeller efficiencies to `0.0` if `power_coefficient` (CP) are very close to `0.0`. 
4. in Aviary docs, add a note for the case shaft power is zero.

### Related Issues

- Resolves #

### Backwards incompatibilities

None

### New Dependencies

None

2024-07-30 00:27 UTC, johnjasa approved these changes
Nice changes, thanks Xun!

2024-07-30 21:35 UTC, jkirk5 commented
This solution raises an error if mission parameters like speed of sound, tip speed, shaft horsepower, etc. go negative - it's pretty easy to imagine a scenario where the optimizer to test a point slightly out of bounds and it will be extremely difficult to debug that if that behavior kills a run.

What's the typical way this is handled in complex openmdao problems? Should we add code to set specific parameters to an arbitrary small positive number if <= 0, then have the propeller builder add a constraint so the optimizer knows it shouldn't be doing that?

2024-07-31 17:16 UTC, jkirk5 requested changes

2024-07-31 17:16 UTC, jkirk5 commented on aviary/subsystems/propulsion/propeller/hamilton_standard.py
> +            raise ValueError("Aircraft.Engine.PROPELLER_DIAMETER must be positive.")
```suggestion
            raise om.AnalysisError("Aircraft.Engine.PROPELLER_DIAMETER must be positive.")
```

2024-07-31 17:16 UTC, jkirk5 commented on aviary/subsystems/propulsion/propeller/hamilton_standard.py
> +            raise ValueError("Dynamic.Mission.PROPELLER_TIP_SPEED must be positive.")
```suggestion
            raise om.AnalysisError("Dynamic.Mission.PROPELLER_TIP_SPEED must be positive.")
```

2024-07-31 17:16 UTC, jkirk5 commented on aviary/subsystems/propulsion/propeller/hamilton_standard.py
> +            raise ValueError("Dynamic.Mission.SPEED_OF_SOUND must be positive.")
```suggestion
            raise om.AnalysisError("Dynamic.Mission.SPEED_OF_SOUND must be positive.")
```

2024-07-31 17:16 UTC, jkirk5 commented on aviary/subsystems/propulsion/propeller/hamilton_standard.py
> +            raise ValueError("Dynamic.Mission.DENSITY must be positive.")
```suggestion
            raise om.AnalysisError("Dynamic.Mission.DENSITY must be positive.")
```

2024-07-31 17:16 UTC, jkirk5 commented on aviary/subsystems/propulsion/propeller/hamilton_standard.py
> +            raise ValueError("Dynamic.Mission.SHAFT_POWER must be non-negative.")
```suggestion
            raise om.AnalysisError("Dynamic.Mission.SHAFT_POWER must be non-negative.")
```

2024-08-01 15:42 UTC, jkirk5 approved these changes

2024-08-01 16:16 UTC, merged