Multi-engine renaming
OpenMDAO/Aviary pull request #471
Opened 2024-07-31 16:45 UTC by johnjasa

### Summary

Renaming any use of `multi-engine` to use homogenous or heterogeneous as appropriate.

### Related Issues

- Resolves #296 

### Backwards incompatibilities

None

### New Dependencies

None

2024-07-31 19:23 UTC, jkirk5 requested changes

2024-07-31 19:23 UTC, jkirk5 commented on aviary/docs/misc_resources/glossary.md
> +    Engines that are assumed to have the same performance characteristics.
```suggestion
    An individual engine or set of engines that all have identical performance characteristics.
```

2024-07-31 19:23 UTC, jkirk5 commented on aviary/docs/misc_resources/glossary.md
> +    Engines that are assumed to have different performance characteristics.
```suggestion
    Multiple sets of homogenous engines, with each set having unique performance characteristics.
```

2024-07-31 19:23 UTC, jkirk5 commented on aviary/docs/misc_resources/glossary.md
> +    This is useful if you are modeling an aircraft with engines of different sizes or types.
```suggestion
    This is useful if you are modeling an aircraft with engines of different sizes or types.
    Each unique engine would use the same `EngineModel` object in Aviary.
```

2024-07-31 19:23 UTC, jkirk5 commented on aviary/mission/flight_phase_builder.py
> +        # For multiple heterogeneous-engine cases, we may have throttle allocation control.
```suggestion
        # For heterogeneous-engine cases, we may have throttle allocation control.
```

2024-07-31 19:23 UTC, jkirk5 commented on aviary/subsystems/aerodynamics/flops_based/skin_friction.py
> +        # TODO does not used vectorized multiple heterogeneous engines. Temp using single engine
```suggestion
        # TODO does not used vectorized heterogeneous engines. Temp using single engine
```

2024-07-31 19:23 UTC, jkirk5 commented on aviary/mission/flight_phase_builder.py
> +        # For multiple heterogeneous-engine cases, we may have throttle allocation control.
Implied an aircraft with heterogeneous engines must have more than one type of engine (can't have single heterogeneous engine)

2024-07-31 19:23 UTC, jkirk5 commented on aviary/subsystems/mass/flops_based/landing_gear.py
> +        # TODO temp using first engine, multiple heterogeneous engines not supported
```suggestion
        # TODO temp using first engine, heterogeneous engines not supported
```

2024-07-31 19:23 UTC, jkirk5 commented on aviary/subsystems/mass/flops_based/landing_gear.py
> +        # TODO temp using first engine, multiple heterogeneous engines not supported
```suggestion
        # TODO temp using first engine, heterogeneous engines not supported
```

2024-07-31 19:23 UTC, jkirk5 commented on aviary/subsystems/propulsion/utils.py
> +                    # we know aviary_values is for multiple heterogeneous engine type. Currently only using
```suggestion
                    # we know aviary_values is for heterogeneous engine type. Currently only using
```

2024-07-31 19:23 UTC, jkirk5 commented on aviary/utils/preprocessors.py
> +    multiple heterogeneous engines.
```suggestion
    heterogeneous engines.
```

2024-07-31 19:23 UTC, jkirk5 commented on aviary/utils/process_input_decks.py
> +        # multiple heterogeneous engine-model case. Get thrust from the engine decks instead.
```suggestion
        # heterogeneous engine-model case. Get thrust from the engine decks instead.
```

2024-07-31 19:23 UTC, jkirk5 commented on aviary/variable_info/variable_meta_data.py
> +# TODO clash with per-engine scaling, need to resolve w/ multiple heterogeneous engine
```suggestion
# TODO clash with per-engine scaling, need to resolve w/ heterogeneous engine
```

2024-07-31 19:23 UTC, jkirk5 commented on aviary/subsystems/mass/flops_based/misc_engine.py
> +    and propulsion-level starter and controls mass, not multiple heterogeneous engines safe!
```suggestion
    and propulsion-level starter and controls mass, not heterogeneous engine safe!
```

2024-07-31 19:23 UTC, jkirk5 commented on aviary/docs/misc_resources/comparison_to_flops.md
> +engines Aviary retains many of the relations used by FLOPS to scale engine mass and
```suggestion
engines, each of which has unique characteristics and can use different methodologies for sizing and performance estimation. Aviary retains many of the relations used by FLOPS to scale engine mass and
```

2024-07-31 19:25 UTC, jkirk5 commented on aviary/docs/misc_resources/glossary.md
> +    Each of these engines would use the same `EngineModel` object in Aviary.
```suggestion
    All engines in a homogenous set use the same `EngineModel` object in Aviary.
```

2024-07-31 20:32 UTC, Kenneth-T-Moore approved these changes
Fix works great.

2024-08-01 19:01 UTC, jkirk5 approved these changes

2024-08-01 19:34 UTC, merged

2024-08-01 23:42 UTC, xjjiang commented
@johnjasa there is usage of  pkg_resources in `docs/user_guide/external_aero.ipynb`