Wetted area got a huge number because multiplication factor is 4000
OpenMDAO/Aviary pull request #510
Opened 2024-08-29 17:12 UTC by xjjiang

### Summary
set `Aircraft.Fuselage.WETTED_AREA_FACTOR = 1.0` because `Aircraft.Fuselage.PROVIDE_SURFACE_AREA = False`. It was set to `4000`.

### Related Issues

- Resolves #

### Backwards incompatibilities

None

### New Dependencies

None

2024-08-29 17:38 UTC, Kenneth-T-Moore approved these changes
Probably makes sense to have reasonable values in the tests. The original test writer may have forgotten to toggle the PROVIDE_SURFACE_AREA flag.

2024-09-03 16:11 UTC, jkirk5 requested changes
Can we change the scale factor to a value that isn't 1.0? That way the test is also making sure we're actually multiplying the scaler correctly

2024-09-03 22:33 UTC, xjjiang commented
Changed one of `Aircraft.Fuselage.WETTED_AREA_FACTOR` to 0.5 from 1.0 to verify it works.

2024-09-04 18:25 UTC, closed without merging

2024-09-04 18:25 UTC, xjjiang commented
This feature will be covered by another PR. So, I am closing it.