Verbosity cleanup roundl;i'
OpenMDAO/Aviary pull request #636
Opened 2024-12-26 19:09 UTC by jkirk5

### Summary

Summary of PR.

### Related Issues

- Resolves #

### Backwards incompatibilities

None

### New Dependencies

None

2024-12-26 19:48 UTC, jkirk5 commented on aviary/interface/methods_for_level2.py
> +        # `self.verbosity` = "true" verbosity for entire run. `verbosity` = verbosity
```suggestion
        # `self.verbosity` is "true" verbosity for entire run. `verbosity` is verbosity
```

2025-01-07 21:53 UTC, Kenneth-T-Moore commented on .gitignore
> +*.openmdao_out
Just want to make sure you know about the `openmdao clean` command, for cleaning up all of these directories.
https://openmdao.org/newdocs/versions/latest/other_useful_docs/om_command.html#openmdao-clean

2025-01-07 21:54 UTC, Kenneth-T-Moore commented on aviary/docs/examples/outputted_phase_info.py
> +phase_info = {
This file is proving to be a problem. I think we need it for some glue stuff, but it is auto-generated, so always has to be fixed every time we run the docs.

2025-01-07 21:55 UTC, Kenneth-T-Moore commented on aviary/docs/getting_started/onboarding_level1.ipynb
> +    "Variable names may be differently within the code from how they are formatted inside OpenMDAO components and in input files and outputs. For example, variable `aircraft:wing:aspect_ratio` in `ai
wording : "may be differently..." --> "may appear differently..."

2025-01-07 22:05 UTC, Kenneth-T-Moore commented on aviary/subsystems/mass/flops_based/wing_detailed.py
> +                inertia_factor[i] = inertia_factor_i[0]
It doesn't look like this should ever become a vector, so if it does, then there is something that should be fixed on one of the variables.

2025-01-07 22:07 UTC, Kenneth-T-Moore commented on aviary/models/large_turboprop_freighter/phase_info.py
> +            'EAS_target': (150, 'kn'),
Kind of some big changes to the turboprop mission.

2025-01-07 22:10 UTC, Kenneth-T-Moore commented on aviary/interface/methods_for_level2.py
> +from aviary.mission.gasp_based.idle_descent_estimation import (
Doing the auto-PEP on this file might make it very difficult to merge the changes into the level 2 refactor that is part of the epic that Eliot is working on.

2025-01-08 19:28 UTC, jkirk5 commented on aviary/interface/methods_for_level2.py
> +from aviary.mission.gasp_based.idle_descent_estimation import (
This PR isn't time sensitive, I don't mind waiting until after that work gets merged in

2025-02-06 23:06 UTC, jkirk5 commented on aviary/models/large_turboprop_freighter/phase_info.py
> +            'EAS_target': (150, 'kn'),
I think this caught an old change to the turboprop phases, Carl updated them at some point and it seems like they should still be 250 as far as I can tell

2025-02-06 23:08 UTC, jkirk5 commented on aviary/models/large_turboprop_freighter/phase_info.py
> +            'EAS_target': (150, 'kn'),
```suggestion
            'EAS_target': (250, 'kn'),
```

2025-02-06 23:10 UTC, jkirk5 commented on aviary/docs/examples/outputted_phase_info.py
> +phase_info = {
The docs appear to run just fine without this file initially being in the repo. I've removed it and was able to build docs without issue

2025-03-10 17:36 UTC, crecine commented on aviary/interface/methods_for_level1.py
> +        If provided, overwrites verbosity specified in aircraft_filename.
```suggestion
        If provided, overwrites verbosity specified in aircraft_data.
```

2025-03-10 17:36 UTC, crecine commented on aviary/utils/functions.py
> +                    aviary_based_path}' as an Aviary package path, checking built-in models"
```suggestion
                f"Unable to locate '{ \
                    aviary_based_path}' as an Aviary package path, checking built-in models"
```

2025-03-27 14:52 UTC, ehariton commented on aviary/interface/methods_for_level1.py
> -        optimization_history_filename=optimization_history_filename, gen_n2=gen_n2)
was removing the n2 generation input here purposeful?

2025-03-27 14:54 UTC, ehariton commented on aviary/interface/test/test_linkage_logic.py
> +    # test = AircraftMissionTestSuite()
did we need to add these comments here?

2025-03-27 15:03 UTC, Kenneth-T-Moore commented on aviary/interface/test/test_linkage_logic.py
> +    # test = AircraftMissionTestSuite()
These are generally helpful for running a test in the debugger, because `unittest` captures all exceptions, preventing you from getting a debug context at the line that fails.

2025-03-27 15:06 UTC, Kenneth-T-Moore commented on aviary/examples/multi_mission/run_multimission_example_large_single_aisle.py
> +    #     (Aircraft.CrewPayload.PASSENGER_MASS, 'lbm'),
Since this is an example, I would just put this whole block of code under an `if show_plots:` conditional. Then, just set show_plots to false above. A user can easily set it to true to see the plots.

2025-03-27 15:17 UTC, ehariton commented on aviary/subsystems/aerodynamics/flops_based/test/test_solved_aero_group.py
> -        subsystem_options = {'method': 'solved_alpha',
These sorts of changes make it really clear to me that we all need to get on the same linting system.

2025-03-27 15:47 UTC, ehariton commented on aviary/utils/process_input_decks.py
> +        from aircraft data or defaulted to Verbosity.BRIEF is not found.
incomplete sentence: "defaulted to Verbosity.BRIEF is not found"

2025-03-27 16:13 UTC, ehariton commented on aviary/utils/csv_data_file.py
> +        controls level of printouts when running this method. Default is BRIEF (1).
Do want to tell the user all the possible options here? All we tell them is BRIEF, but there are many other options. Is there a different place that this information is presented?

2025-03-27 16:24 UTC, ehariton commented on aviary/variable_info/variable_meta_data.py
> +    'system mass added to engine control and starter mass, or used to '
is this an incorrect tabbing update?

2025-03-27 16:55 UTC, ehariton commented on aviary/interface/methods_for_level2.py
> +        # might try and include it (only method that doesn't accept it). Capture it
nice catch

2025-03-27 17:00 UTC, ehariton commented on aviary/interface/methods_for_level2.py
> +                        self.phase_info[phase_name]["user_options"].update(
This expansion seems a bit excessive.

2025-03-27 17:05 UTC, ehariton commented on aviary/interface/methods_for_level2.py
> -        if gen_n2:
ok I see now, you are generating the n2 regardless.

2025-03-27 17:06 UTC, ehariton commented on aviary/interface/methods_for_level2.py
> +    def fallout_mission(
I really don't like this expanded format, it doesn't add anything and takes up waay too many lines of code.

2025-03-27 17:19 UTC, ehariton commented on aviary/utils/preprocessors.py
> +    ) < aviary_options.get_val(Aircraft.CrewPayload.NUM_FIRST_CLASS):
indentation doesn't look correct here

2025-03-27 17:39 UTC, ehariton commented on aviary/subsystems/mass/gasp_based/design_load.py
> +            np.pi
not again!!!

2025-03-27 17:42 UTC, ehariton commented on aviary/models/N3CC/N3CC_data.py
> +landing_subsystem_options = {
this is an issue.

2025-03-27 17:43 UTC, ehariton requested changes
We need better linting on this PR. It's exploding the side of some lines and being overly verbose, and then in other cases if() statements look really strange, and in some cases it's compressing arrays correctly.

2025-03-27 18:47 UTC, jkirk5 commented on aviary/interface/test/test_linkage_logic.py
> +    # test = AircraftMissionTestSuite()
I can remove. They don't really harm anything, and make it quick to set up for debugging the test (debug mode won't while running `unittest.main()`)

2025-03-27 18:56 UTC, jkirk5 commented on aviary/subsystems/aerodynamics/flops_based/test/test_solved_aero_group.py
> -        subsystem_options = {'method': 'solved_alpha',
Part of it also that code seems to be able to pass the pre-commit check without actually having the formatter run on the code - I see all the time compliant code that suddenly changes when I actually run autopep8 on it.

Although I think I used black on this one, it seems to do a much better job actually splitting lines in a consistent/non-crazy way. Agreed on better standardization needed (I'd vote for ruff)

2025-03-27 19:00 UTC, jkirk5 commented on aviary/interface/test/test_download_models.py
> +        for filename in filenames:
It took me awhile to remember why I did this, but I recall now. The issue was that the actual function call itself was never tested in isolation, and this test was doing the same thing as the interface test, which was calling the CLI. We need tests that validate the python code itself, and a separate test to make sure the command call works - it was very frustrating to try and debug that function only to realize there is no debuggable python call to the util itself (since it's totally valid to use that functionality as a script too.

2025-03-27 20:16 UTC, jkirk5 commented on aviary/utils/csv_data_file.py
> +        controls level of printouts when running this method. Default is BRIEF (1).
The verbosity levels are covered in the docs, and in the variable metadata. We could probably add more detail to some of the docstrings, but it would pop up in a ton of places. Maybe just at the highest levels (like methods_for_level1)

2025-03-27 20:23 UTC, jkirk5 commented on aviary/utils/preprocessors.py
> +    ) < aviary_options.get_val(Aircraft.CrewPayload.NUM_FIRST_CLASS):
It does look a little odd. I guess it's technically consistent with how that code style works, which is that broken up parantheticals place the closing parentheses at the same indentation level as the originating line. Basically, seems like the formatter is trying to keep all the code at the same indentation level as the original line to avoid confusing it for the indented code that occurs inside the `if` statement

2025-03-27 20:42 UTC, jkirk5 commented on aviary/subsystems/mass/flops_based/wing_detailed.py
> +                inertia_factor[i] = inertia_factor_i
At some point there was an issue where this value was a vector when it wasn't supposed to be, which should be fixed now, although I don't remember the specifics, this edit is 2 months old

2025-03-28 14:27 UTC, jkirk5 commented
> We need better linting on this PR. It's exploding the side of some lines and being overly verbose, and then in other cases if() statements look really strange, and in some cases it's compressing arrays correctly.

"better" is hard to define. IMO we pick a formatting style we should always follow it, and that sometimes makes lines look odd. If we're not happy with the styles enforced by autoformaters, the alternative is to manually format a hundred files here, and then you still have the issue that a given style doesn't work well on every line (and implementation will be very inconsistent). I'd support picking a specific formatter, formatting the entire codebase in that style, and enforcing it more strictly going forward. Probably increase the character line limit to 100 as well.

2025-04-01 18:03 UTC, Kenneth-T-Moore commented
I guess everyone knows my preference against using any auto-code formatter. At least that way, we don't have dueling formatters.

2025-04-03 15:08 UTC, Kenneth-T-Moore approved these changes
I think this is good, and the linting can be a later discussion.  Note: there is a conflict with latest main.

2025-04-04 20:27 UTC, merged